### ISSUE TITLE
Request for Docker Deployment Guide for Anyaasi on VPS

### ISSUE THREAD

**Issue by Mustafarexdo** [kstarmach/anyaasi#1]
Thank you for the great project! I would like to request a Docker setup or installation guide for Anyaasi. Having a Docker configuration would make deployment on a VPS much easier and more efficient.

Please consider adding a Dockerfile or documentation for this. Thank you!

**Comment by kstarmach** [comment]
Thank you for the kind feedback on the project!

I appreciate the suggestion about Docker configuration. This is definitely something that will make deployment much easier.

I am currently planning to rewrite the README file, and will definitely consider adding Docker instructions.

I will keep you updated on progress. Thanks again for your feedback!

**Comment by Mustafarexdo** [comment]
Thank you for considering my suggestion! I truly appreciate the time and effort you're putting into improving the project. Please take your time with the Docker setup—I’m sure it will be worth the wait. I look forward to seeing the updated README when it's ready. Thanks again for your hard work and dedication!

**Comment by kstarmach** [comment]
Sorry it took me so long to do this :/
I just added Docker support and rewrote the README file with instructions on how to run docker-compose.yml on the VPS 

Check it out and let me know if you have more questions or suggestions! I'm always willing to help :)

**Comment by Mustafarexdo** [comment]
Thanks for your hard work!!
